version: '3.9'
services:
  todo-app:
    image: our-first-dockerfile-mysql
    ports:
      - 3000:3000
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos
    networks:
      - todo-app-network
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: todos
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - todo-mysql-data:/var/lib/mysql
    networks:
      - todo-app-network
volumes:
  todo-mysql-data:
networks:
  todo-app-network:
    driver: bridge
